### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by ghost** [jkang215/prj-rev-bwfs-dasmoto#5]
https://github.com/jkang215/prj-rev-bwfs-dasmoto/blob/master/Dasmoto/resources/css/style.css#L13-L32

You should not be repeating so much code, since these #brushes, #frames, and #paint all share a majority of common styles. Move common styles into a more general selector:

```css
h2 {
  color: white;
  font-size: 32px;
  font-weight: bold;
}
```

Then you can remove these styles from the other three selectors.
